[project]
name = "lgraph-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "django>=5.2,<5.3",
    "djangorestframework>=3.16,<3.17",
    "langgraph>=1.0.6",
]
